name: Java Test

on: push

permissions:
  contents: read

jobs:
  build:
    name: Build Java project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    
    - name: Test
      run: gradle test

    - name: Publish test report
      uses: dorny/test-reporter@v1
      with:
        name: JUnit-report
        path: '${{ github.workspace }}/build/test-results/TEST-*.xml'
        fail-on-error: true
        reporter: java-junit
